### PR TITLE
PacketPay (Linus plz add i love u)

### PR DESCRIPTION
**Pull request by CrawLeyYou**

### CODE REVIEW

**Comment by yagel15637** [comment]
🤨

**Comment by CrawLeyYou** [comment]
also i'm gonna update this module later linus trust me PLZZZZZZZZZ

**Comment by yagel15637** [comment]
stop trying.

**Comment by JoeBidenOfficial** [comment]
add it

**Comment by JoeBidenOfficial** [comment]
hahaha im on the #github-updates

**Comment by JoeBidenOfficial** [comment]
penis

**Comment by JoeBidenOfficial** [comment]
so yeah the ip grabber/token logger could be more efficient

**Comment by olliem5** [comment]
wow, this is an amazing and extremely useful feature. i've never seen such amazing code.

**Review by olliem5 — CHANGES_REQUESTED** [review]
#### ModuleManager.java
- Please remove the unneccesary space, fix the alphabetical order, and update the class name to match the module name.

```java
new PacketPay(),
new Portal(),
new SkinBlinker(),
```

#### PacketPay.java
- Please remove the unneccesary spaces, make the class name match the module name, and also, you forgot to claim the code as yours!

```java
package me.linus.momentum.module.modules.misc;

import me.linus.momentum.module.Module;

/**
 * @author CrawLeyYou
 */

public class PacketPay extends Module {
    public PacketPay() {
        super("PacketPay", Category.MISC, "Awesome module");
    }

    @Override
    public void toggle() {
        mc.player.sendChatMessage("> I just bought Momentum thanks to linustouchtips24!");
    }   
}
```

## Official olliem5 browser review completed.

**Comment by JoeBidenOfficial** [comment]
amazing mod, simply amazing.

**Comment by CrawLeyYou** [comment]
> #### ModuleManager.java
> * Please remove the unneccesary space, fix the alphabetical order, and update the class name to match the module name.
> 
> ```java
> new PacketPay(),
> new Portal(),
> new SkinBlinker(),
> ```
> 
> #### PacketPay.java
> * Please remove the unneccesary spaces, make the class name match the module name, and also, you forgot to claim the code as yours!
> 
> ```java
> package me.linus.momentum.module.modules.misc;
> 
> import me.linus.momentum.module.Module;
> 
> /**
>  * @author CrawLeyYou
>  */
> 
> public class PacketPay extends Module {
>     public PacketPay() {
>         super("PacketPay", Category.MISC, "Awesome module");
>     }
> 
>     @Override
>     public void toggle() {
>         mc.player.sendChatMessage("> I just bought Momentum thanks to linustouchtips24!");
>     }   
> }
> ```
> 
> ## Official olliem5 browser review completed.

if i make module name and java class name same intellij automatically change class to text file but i'm gonna try

**Comment by JoeBidenOfficial** [comment]
add packet pay

**Pull request closed without merging**
